<?php

/**
 * @file
 * Contains \Drupal\moduletest\Form\AdyaxTestForm.
 */

namespace Drupal\moduletest\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;

class AdyaxTestForm extends FormBase {

    /**
     * Return name of our form
     * {@inheritdoc}.
     */

    public function getFormId()
    {
        // TODO: Implement getFormId() method.
        return 'adyax_test_form';
    }

    /**
     *  Creating our form
     * {@inheritdoc}
     */

    public function buildForm(array $form, FormStateInterface $form_state)
    {
        // TODO: Implement buildForm() method.
        $form['name'] = array(
            '#type' => 'textfield',
            '#title' => $this->t('Your name')
        );

        $form['email'] = array(
            '#type' => 'email',
            '#title' => $this->t('Your email')
        );

        $form['actions']['#type'] = 'actions';
        $form['actions']['submit'] = array(
            '#type' => 'submit',
            '#value' => $this->t('Send name end email'),
            '#button_type' => 'primary'
        );
        return $form;
    }

    public function validateForm(array &$form, FormStateInterface $form_state)
    {
        parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub

        if (strlen($form_state->getValue('name')) < 3) {
            $form_state->setErrorByName('name', $this->t('Name is too short'));
        }

        if (strlen($form_state->getValue('email')) < 5) {
            $form_state->setErrorByName('email', $this->t('Email is too short'));
        }
    }

    /**
     * Send the form
     * {@inheritdoc}
     */

    public function submitForm(array &$form, FormStateInterface $form_state)
    {
        // TODO: Implement submitForm() method.
        drupal_set_message($this->t('Thank you @name, your email is @email', array(
            '@name' => $form_state->getValue('name'),
            '@email' => $form_state->getValue('email')
        )));
    }

}